### ISSUE TITLE
BUG | goto does not animate smoothscroll

### ISSUE THREAD

**Issue by louisgv** [luispuig/react-snaplist-carousel#21]
At the moment, goToSnapItem does not animate, but simply move right to the next item. Ideally, it should animate the slide.

**Comment by louisgv** [comment]
I went thru the code and saw that there's smooth scroll polyfill and scrollto usage in the library. However, when I tried it on Google Chrome on Windows 10, it did not work.

**Comment by louisgv** [comment]
Using the exact codesandbox from #9 
![carousel-notscroll-1](https://user-images.githubusercontent.com/6723574/82768961-01b70800-9de7-11ea-8956-a446670bb2f3.gif)

**Comment by luispuig** [comment]
It is supose to do it. I hade a problem from time to time only in the codesandbox but this one is working well for me:
![May-25-2020 09-19-53](https://user-images.githubusercontent.com/24297787/82788533-ec82bd80-9e68-11ea-97e2-22ec39942da7.gif)
At this point, I am not sure if it is a problem inside codesandbox or a bug I didn't find. As you say, the library uses the scroll native smooth option when it is available and a polyfill when not.
Are the examples out to the codesandbox working well for you? https://luispuig.github.io/react-snaplist-carousel/

codesandbox link: https://codesandbox.io/s/dazzling-butterfly-9iqss

**Comment by louisgv** [comment]
I tried the code sandbox you provided and the result was exactly the same as my previous screencap, very weird behavior. I will try with another device and OS and will report back my finding.

**Comment by luispuig** [comment]
Thanks, looking forward.

**Comment by louisgv** [comment]
It does work on Chrome for Android 10

**Comment by luispuig** [comment]
So, it is working well on Chrome for Android 10. Do we have a conclusión on the SO where it fails?

**Comment by luispuig** [comment]
I did a test on Google Chrome on Windows 10, it was working well.

**Comment by vladimirgorshunov** [comment]
Hi, @luispuig, great job with carousel overall!
I noticed similar issue in Safari Technology Preview and Safari on macOS Big Sur. 
Maybe it's just a bug, but good to keep in mind. 🙂

**Comment by luispuig** [comment]
@vladimirgorshunov , thanks for reporting it. Maybe there is a bug, I wasn't able to reproduce it to dig deeper.

Please, if can reproduce it and try to find the problem it would be very helpful for everybody.
