### ISSUE TITLE
BC Break in 3.1.0

### ISSUE THREAD

**Issue by cryptiklemur** [luispuig/react-snaplist-carousel#23]
https://github.com/luispuig/react-snaplist-carousel/commit/a2d23d6b804dcab1da9520db8edc746c6837f23e#diff-e3457effa5fa347d185fdd0d08ba3209R173

FYI, this should have been a 4.0.0 release.

**Comment by luispuig** [comment]
I see, my bad :(

Shall I bump a new version now even with no more changes? Or leave like this and bump to 4.0.0 next time? Not sure what would be better...

Thanks for reporting it

**Comment by luispuig** [comment]
Bumped on PR https://github.com/luispuig/react-snaplist-carousel/pull/28
