### ISSUE TITLE
Suggestion: Make a optional second argument for goTo for animation time

### ISSUE THREAD

**Issue by tinglof** [luispuig/react-snaplist-carousel#24]
Hello there, thanks for a great component. 

I have a suggestion, if you could pass a second argument like animationTime or a boolean to disable animation to the method returned by the useScrollHook, then you would be able to use that on mount. 

A use case for this would be if you have saved which item that is scrolled to on a page or if you want to start with another item than the first scrolled to. If you do it now with the method in the component it will show a bit of flickering since there is a hardcoded animation time of 350 ms.

What do you think about it? Want me to make a PR?

**Comment by luispuig** [comment]
Hi @tinglof,

Thanks a lot for the suggestion, it seems very useful for many use cases.

Would be great if you can prepare the PR and having you as a contributor.

A couple of things to take into account:
- Please, make the second parameter to be an object to allow more future options: goTo(element, {option: true, option2: false})
- The scroll will use the browser native speed for the browsers that support the smooth option. In this case, we will need to scroll without `behavior: 'smooth'`. For the others, there is a polyfill that uses those 350ms. 

https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior
https://github.com/luispuig/react-snaplist-carousel/blob/master/src/smoothScroll.ts#L81

Looking forward to your code

**Comment by tinglof** [comment]
@luispuig Perfect, thanks for the input. I have a pretty intense work week ahead but will try to do it as soon as I have some spare time not spent on relaxing :)

**Comment by luispuig** [comment]
😄 Take your time! Let me know if I can help with it.

**Comment by luispuig** [comment]
Implemented https://github.com/luispuig/react-snaplist-carousel/pull/31
