### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by michal-olchawa-360codelab** [luispuig/react-snaplist-carousel#26]
Hi! First of all, nice work with this component.

Wanted to use this in own project as it looks very promising but there is one thing that's preventing me from doing it - I am not able to have styles from CSS file applied on server side render but they get injected when script is executed in the browser instead.
Imho it would be good if e.g. it would be possible to load css files with own bundler (with proper classes generated) or have `<style>` tag inserted on `<SnapList>` render inside the component and moved to head on hydration. That are just quick ideas but the general idea is to have some mechanism to avoid flash of unstyled snaplist carousel.

What do you think about this?
Cheers

**Comment by luispuig** [comment]
Adding support for SSR would be great. I have no experience with SSR, can you help with the implementation?

The library is using CSS Modules for the implementation. I saw https://stackoverflow.com/questions/34615898/react-server-side-rendering-of-css-modules it can be helpful information.
