### ISSUE TITLE
viewport left / right is miscalculated on Android Chrome

### ISSUE THREAD

**Issue by gajus** [luispuig/react-snaplist-carousel#27]
There is weird bug where viewport `left` and `right` values are miscalculated.

https://github.com/luispuig/react-snaplist-carousel/blob/master/src/useVisibleElements.ts#L35-L36

If card position is 450 then when the element is scrolled into the `viewport.left` is going to be some similar number with a fraction, e.g. 450.345.

As far as I can tell, simply using `floor` and `ceil` to round down / up the numbers fixes the problem, i.e. I locally patched this library to use the following condition:

```js
const isVisibleHorizontally = item.left >= Math.floor(viewport.left) && item.right <= Math.ceil(viewport.right);
```

**Comment by luispuig** [comment]
That is a great catch! 

Do you want to make the PR and do your contribution or do you want me to do it?

**Comment by gajus** [comment]
Go for it. For small things like this it will be easier for you to just publish the changes.

**Comment by luispuig** [comment]
Version 4.0.0 deployed.

Thanks for your help and contribution!

**Comment by gajus** [comment]
Thank you!
