### ISSUE TITLE
Create A Placeholder SnapItem (for offset) or change the Style of SnapItem

### ISSUE THREAD

**Issue by nicseve** [luispuig/react-snaplist-carousel#34]
I have a somewhat unique scenario where the user needs to swipe (drag) up or down on a page to reveal information above or below the page's visible content. The information above and below is specific to the content that is initially visible so I need all of the data to be contained within one snap item (since changing/syncing the above or below data based on the state/visible content within the snaplist (solely through scrolling) is more difficult). How can I create an invisible snap item or create a placeholder snap item to offset the content in the snap list but still create the illusion that the content is a separate snap item and thus get the gesture to display the above or below data properly?

**Comment by luispuig** [comment]
Sorry. I am not sure I understood properly your use case. If you can elaborate a bit more I can try to help.

**Comment by nicseve** [comment]
Sure. Imagine two snaplist: one that scrolls vertical and another inside of it that scrolls horizontal. So the user can swipe left and right and up and down to reveal content above and below the page. The inner, horizontal snaplist has snapitems whose height is greater than the initial page size so when the user swipes up or down the snapitem's upper or lower content is revealed.  

The issue is I can't control the outer, vertical  snaplist's snap point or offset it to make inner snapitem's upper or lower content appear correctly. I tried to use a placeholder snapitem above the inner horizontal snaplist and play with the margins but this doesn't work because the placeholder snapitem (even tho it is empty) cuts off any content that overlaps with it.

**Comment by luispuig** [comment]
It is difficult for me to imagine it. If you share a repo or something I can try to take a look at it.

**Comment by nicseve** [comment]
Sure so here is a snippet of what I have. There are two snaplists (for top and bottom users that can slide left and right) nested inside a vertical snaplist ideally so the entire screen can slide up and down to reveal content)
`           <SnapList direction="vertical" height={650} width={275} ref={snapListVertical}>
                    <div style={{marginTop: 5}}>
                        <SnapItem height={570} margin={{bottom: '420px'}} snapAlign="center">
                            <div style={{position: 'relative', width: 260, bottom: 10}}>
                                <SnapList ref={snapList} direction="horizontal" width={260}>
                                    {topUsersSnapItems}
                                </SnapList>
                            </div>
                            <div style={{position: 'relative', width: '100%', top: 100, right: 250}}>
                                <SnapList ref={snapList1} direction="horizontal"
                                          width={260}>
                                    {bottomUsersSnapItems}
                                </SnapList>
                            </div>`

Here are visual mocks that show the entire screen sliding up to reveal a paragraph for a given snap item.
![image](https://user-images.githubusercontent.com/13892332/131230515-e29def25-2dba-4083-b8c0-9f5d4c966e2f.png)
![image](https://user-images.githubusercontent.com/13892332/131230517-92b1b605-2823-4190-b5e7-f8d18d511c8b.png)
![image](https://user-images.githubusercontent.com/13892332/131230522-809d7606-bb2c-45c8-9f66-d38ed0679c11.png)

**Comment by luispuig** [comment]
Hello,

I am not sure if I understood exactly your need but I saw a few issues:
* SnapList must have all the children to be SnapItem, you cannot put divs in the between.
* The width and height must be strings: “650px”

I created a code sandbox with a workable example implementing what I understood. I hope it helps.
![Aug-31-2021 09-45-16](https://user-images.githubusercontent.com/24297787/131463679-891e45a5-822e-43db-8466-f8f518fe1b6b.gif)

https://codesandbox.io/s/clever-star-9ddc2?file=/src/App.js

**Comment by nicseve** [comment]
Thanks for the working example. Unfortunately it doesn't do what I am trying to. Your example only shows one snaplist at a time, I need to show two horizontally scrollable snaplists on the page when the user is in the middle item.

That's why the divs are there, to allow for the two horizontal snaplists to overlap. Otherwise the snaplists do not allow for any kind of overlap with other content. I think my problem would be solved if I could change the snap point of the snaplist or position the snap items within the snaplist with more than just margins. 

Closing this since it seems to be a special case. Could you possibly share an example of how to override the style of both of the snaplist and snapitmes that would allow me to remove the divs and get more control over the snapitem positions or opacity?
