### ISSUE TITLE
[Safari] Using useScroll to navigate through elements won't work in Safari 15.4

### ISSUE THREAD

**Issue by Senol122** [luispuig/react-snaplist-carousel#47]
In my app, I used the useScroll hook to navigate through elements of the carousel. It worked as fine as it could.

A couple days ago some users reported that they could not navigate through the carousel. I did some investigating, and found out that the issue happens only on Safari 15.4.

Again, I did some digging and I found out that Safari does not support to set scroll behavior in the later versions.

A workaround I found to make things work on Safari 15.4 was to change the smoothScroll method from the library in the following way:
```
var smoothScroll = function (node, scrollTarget, duration) {
    if (!node)
        return;
    if (hasNativeSmoothScroll()) {
        return node.scrollTo({
            left: scrollTarget.left,
            top: scrollTarget.top,
            behavior: 'auto',
        });
    }
    else {
        return smoothScrollPolyfill({ node: node, scrollTarget: scrollTarget, duration: duration });
    }
};
```

, where `behavior: 'auto'` fixes the issue. Hope this helps others, and I hope some of you can find better solutions to keep smooth scrolling where it can be used.

**Comment by luispuig** [comment]
Hi @Senol122,

We are checking it. It seems that Safari added support for smooth but it is not working well. https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes#Web-API

Best regards,

Luis Puig

**Comment by luispuig** [comment]
It was an error on Safari that is fixed in the last Safari version. I'll close this issue.
