### ISSUE TITLE
Incompatibility with React 18 + typescript 

### ISSUE THREAD

**Issue by tom-sanderson-bt** [luispuig/react-snaplist-carousel#54]
Children now needs declaring as a prop , and the current typescript definition is not allowing `<SnapItem />` to have children.

Also looking at the implementation `snapAlign` could be optional , as it has a default value.

**Comment by Zanabitti** [comment]
Is there a way to extend the type in my own .d.ts somehow?

**Comment by luispuig** [comment]
Would you mind making a PR to this repo with the fix? Thanks
