### ISSUE TITLE
Proximity snap

### ISSUE THREAD

**Issue by equinusocio** [luispuig/react-snaplist-carousel#66]
Hello, it would be useful to have a way to set `proximity` snap instead of `mandatory`. Like a new prop on the Snaplist.

**Comment by luispuig** [comment]
Hi! Yeah, it could be helpful. Would you like to make a contribution?

**Comment by equinusocio** [comment]
Only if you mind to merge it and not let it die.

**Comment by luispuig** [comment]
Sure! especially if it is optional/configurable :)

**Comment by equinusocio** [comment]
Done, with some extra

**Comment by equinusocio** [comment]
Did you find the time to check the pr?

**Comment by luispuig** [comment]
Sorry, we have been in public days. This week I'll check it and merge it.

**Comment by luispuig** [comment]
Deployed! Thanks a lot for the contribution!
