### ISSUE TITLE
SnapList height

### ISSUE THREAD

**Issue by srikxr** [luispuig/react-snaplist-carousel#68]
Hey there, how can I reduce the default height of the snap list? It seems like it is taking up more space than I want it to. I have tried to put in height within the styling of it, but it did not do anything. Would love some help with this. 

Here is an image of what is going on:
![image](https://github.com/luispuig/react-snaplist-carousel/assets/21000713/8c82c8b8-ee4e-404e-8578-8672b84c88b7)

here is my code for snaplist: 

      <SnapList
                ref={snapList}
                direction="horizontal"
                onScroll={handleScroll}
              >
                {data.map((mission, index) => {
                  const toDate = moment.utc(mission.toDate).startOf("day");
                  const currentDate = moment.utc().startOf("day");
                  const remainingDays = toDate.diff(currentDate, "days");

                  return (
                    <SnapItem
                      key={index}
                      margin={{ left: "1rem", right: "1rem" }}
                    >
                      <div
                        className="h-[238px] w-[268px] bg-cover rounded-2xl"
                        style={{
                          backgroundImage: `url(${mission.missionImageURL})`,
                        }}
                        onClick={() => openModal(mission)}
                      >
                        <MissionComponent
                          image={mission.missionImageURL}
                          title={mission.missionName}
                          reward={mission.rewardAmount}
                          missionType={mission.missionTypeName}
                          remainingDays={remainingDays}
                        />
                      </div>
                    </SnapItem>
                  );
                })}
              </SnapList>

**Comment by luispuig** [comment]
SnapList has a height property https://github.com/luispuig/react-snaplist-carousel#snaplist . Would it work for you?
