### ISSUE TITLE
Can not scroll on PC/Laptop with direction="horizontal"

### ISSUE THREAD

**Issue by nguyenhoaidanh** [luispuig/react-snaplist-carousel#83]
on Mobile it work well

**Comment by luispuig** [comment]
Hi!

Are these examples working for you? https://luispuig.github.io/react-snaplist-carousel/

Did you enable drag&drop with `useDragToScroll`? Hopefully, this is the issue.

**Comment by nguyenhoaidanh** [comment]
yeah, good to know.
I work with useDragToScroll.
Thanks a lot.
