### ISSUE TITLE
Carousel does not seem to work if wrapped by a position: absolute div

### ISSUE THREAD

**Issue by jlison** [luispuig/react-snaplist-carousel#9]
Hi Luis,

Thank you for creating this really cool carousel package 🙂. While I was testing it, I realized that the carousel does not seem to work if I wrap it in a `div` with `style={{ position: "absolute" }}`. If I remove the wrapping `div` it seems to work fine. Is that expected? 

Example: https://codesandbox.io/s/musing-glitter-owv4z

¡Saludos!

**Comment by luispuig** [comment]
Hello @jlison ,

I am glad you like the library. It seems to be a problem with the size of the wrapper, it needs a set.

If you try `style={{ position: "absolute"; width: "100% }}` it works.

Example: [https://codesandbox.io/s/dazzling-butterfly-9iqss](https://codesandbox.io/s/dazzling-butterfly-9iqss)

**Comment by jlison** [comment]
That makes sense! 🙂👍 Thank you for your prompt response.
